### ISSUE TITLE
33 covariate limit on brms model with random slopes?

### ISSUE THREAD

**Issue by openpencil** [paul-buerkner/brms#100]
Dear Paul,

I am trying<sup id="f1">[1](#my_brms_code)</sup> to fit the following multinomial model with brms for a high-dimensional dataset with more than 80 variables:

`
y ~ 0 + trait + trait:(x1 + x2 + x3 + ... + x80) + (1 + x1 + x2  + x3 ... + x80|individual)
`

where `x1, x2, x3 ... x80` are the 80 covariates.

It turns out that if there are more than 33 covariates, `brms` throws the following error:  
`Random effects terms should be enclosed in brackets.`

However, the model runs without a hitch when there are <= 33 covariates. So I don't think it is an issue with the brackets at all. In searching for this error<sup id="f2">[2](#error_search_in_brms)</sup> in the `brms` codebase, I can see the error message in the following testing scripts. 

`tests/testthat/tests.validate.R`

`R/validate.R` 

Could you please investigate whenever you get a chance?

Thanks so much!

best,
Jyoti

Links:

<b id="my_brms_code">1. </b> https://github.com/openpencil/bmixr/blob/master/bmixr_buildbrms.R [↩](#f1)

<b id="error_search_in_brms">2.</b>
https://github.com/paul-buerkner/brms/search?utf8=%E2%9C%93&q=%22Random+effects+terms+should+be+enclosed+in+brackets%22  [↩](#f2)

**Comment by paul-buerkner** [comment]
Thanks for reporting the error! I already have an idea on what's happening and will tell you as soon as I fixed it.

**Comment by paul-buerkner** [comment]
When you call 

```R
vars <- paste0("x", 1:80, collapse = "+")
form <- paste0("y ~ 0 + trait + trait:(", vars, ") + (1 + ", vars, "|individual)")
form <- formula(form)
brms:::extract_effects(form)
```

does it produce the error? If yes, I have already fixed it in the current dev version while refactoring some functions related to formula parsing. In this case, you can just go ahead and install the dev version from github via `devtools::install_github("paul-buerkner/brms")`.

**Comment by openpencil** [comment]
Many thanks for looking into this bug! I can confirm that the code you have pasted above does produce the same error.  I also uninstalled the CRAN version of `brms` and installed the devtools version as you have indicated above. It doesn't seem to help matters and I still get the same bug at >33 variables. Am I missing something here?

This is my call:
```
formula <- paste(sprintf("response ~ 0 + trait + trait:(%s)", covariate_vector), 
sprintf("(1+%s|randomeffects_term)", covariate_vector), sep = " + ")

mixed_model <- brm(formula = as.formula(formula), data = regdata, 
                                    family = brms_family, cores = numcores, 
                                    chains = numcores, iter = numiter, 
                                    warmup = 0.1*numiter, prior = type_of_prior,
                                    control = list(max_treedepth = treedepth, 
                                    adapt_delta = adaptdelta))
```
where `covariate_vector` consists of the 80 variables.

Thanks for any insight!
best,
Jyoti

**Comment by paul-buerkner** [comment]
That's weird because the code I posted above runs without error for me with the dev version of brms. When I call 

```R
covariate_vector <- paste0("x", 1:80, collapse = "+")
formula <- paste(sprintf("y ~ 0 + trait + trait:(%s)", covariate_vector), 
                 sprintf("(1+%s|id)", covariate_vector), sep = " + ")
regdata <- as.data.frame(matrix(rnorm(800), nrow = 10, ncol = 80))
names(regdata) <-  paste0("x", 1:80)
regdata$y <- sample(1:3, 10, TRUE)
regdata$id <- rep(1:2, each = 5)

mixed_model <- brm(formula = as.formula(formula), data = regdata,
                   family = categorical())
```

the model compiles without any complaints in the dev version. Can you check again that you have the latest dev version (if `brms::bf(y~x, sigma = ~1)` doesn't result in an error, you should have it)?

**Comment by openpencil** [comment]
I was able to successfully run the code above with the new version of brms. However, when I switch to my dataset, the error appears again. I am investigating this - could be one of the column names that is throwing a spanner in the works for formula().  I will report back! Thanks again for all your help!!

**Comment by openpencil** [comment]
So the bug is still around. Try this code using your new version:
```R
covariate_vector <- paste0("xxxxx", 1:80, collapse = "+")
formula <- paste(sprintf("y ~ 0 + trait + trait:(%s)", covariate_vector),
                 sprintf("(1+%s|id)", covariate_vector), sep = " + ")
brms:::extract_effects(formula = as.formula(formula))
```
The only difference between your code and the above code is the length of the variable names. e.g. `xxxxx80` vs `x80`

**Comment by paul-buerkner** [comment]
It should be fixed now. The problem was that the `terms` function adds linebreaks to very long term labels, which led to a failure in my formula parsing. I don't see why it is desireble to have those linebreaks, but the R developers probably had something in mind when doing this...

Anyway, I have improved the way special terms (including random effects) are parsed in `extract_effects` and it should now work reliably independent of the length of the terms. As soon as you verify that it works correctly with your models, I think we can close this issue.

**Comment by openpencil** [comment]
Dear Paul,

I am confirming that the newest version works with my datasets. Thanks SO very much for helping me with this bug!  Thanks also for creating this very accessible interface to STAN and for continuing to improve it so diligently. 

Your package is helping my research in so many ways. For example, the interesting preliminary insights I obtained as part of analysis for [this poster] (https://github.com/openpencil/openpencil.github.io/raw/master/assets/ICML2016_jshankar_06222016.pdf) (presented at ICML2016, Compbio Workshop) was primarily through `brms` models. I am currently working on extending this analysis and will keep you posted on where the story goes! :-)
 
best regards,
Jyoti

**Comment by paul-buerkner** [comment]
I am glad that it is working correctly now! 

I am happy to hear from you whenever you have questions / ideas or just want to show me what you have done. The poster looks great by the way! :-)
