### ISSUE TITLE
Uninformative error message after forgetting `stan_funs` argument

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#241]
I'm using `brms` to fit a nonlinear model which uses some custom functions defined in a `stan_funs` character string. When calling `brm` I forgot to include this character string in the `stan_funs` argument, and received the following error message:

```r
Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname, : c++ exception (unknown reason)
```

It took me a few minutes to figure out the problem. Perhaps this error could be made more informative?

**Comment by tomwallis** [comment]
EDIT: this is not just an error for forgetting to pass `stan_funs`, but similar errors occur if the functions defined in `stan_funs` are somehow invalid stan code. I guess returning informative error messages from `rstan` is a deeper problem than I had thought.

**Comment by paul-buerkner** [comment]
I believe this is a problem in Stan that was resolved in rstan version 2.16. When I am using a function that is not defined, I get an informative error message from the Stan parser.

**Comment by paul-buerkner** [comment]
Also, `brm` suppresses some error messages of the Stan parser, so that calling `make_stancode` once when doing something non-standard might be helpful in debugging.

**Comment by tomwallis** [comment]
Ah, that could be – I'm still on `rstan` v 2.15.1. I didn't mention in my first reply above but I did check `make_stancode` and got the same uninformative error. I will try upgrading `rstan` and seeing if I still have the problem.
