### ISSUE TITLE
Categorical predictions with original factor labels

### ISSUE THREAD

**Issue by mjskay** [paul-buerkner/brms#497]
#491 reminded me of a minor issue I've been meaning to ask about: is it possible to (or possible to add a way to) get predictions from brms ordinal/categorical models that use the original factor labels? Currently all methods I've tried for `predict.brmsfit` and `fitted.brmsfit` give numerical levels instead of using the names of levels from the original response variable.

See e.g. [this example](https://mjskay.github.io/tidybayes/articles/tidy-brms.html#ordinal-model-with-continuous-predictor) from tidybayes (which uses `fitted.brmsfit` with `summary = FALSE` under the hood), and requires this ugly line to relabel the fit categories:

```r
...
  mutate(cyl = ordered(.category, labels = levels(ordered(mtcars$cyl)))) %>%
...
```

Which it would be nice to be able to omit.

**Comment by paul-buerkner** [comment]
Would it suffice if the 3rd dimension of the returned array returned the names of the categories?

**Comment by paul-buerkner** [comment]
It should be working now. If you verified it fulfills its purpose, feel free to close this issue.

**Comment by mjskay** [comment]
Perfect, that works, thanks!

**Comment by mjskay** [comment]
I've noticed two possible issues with this:

1. `predict()` does not also use the factor names. E.g. with `fitted()` you now get level names from the original factor:

    ```r
    m_cyl_mpg = brm(ordered(paste0("c", cyl)) ~ mpg, data = mtcars, family = cumulative)
    str(fitted(m_cyl_mpg))
    # num [1:32, 1:4, 1:3] 0.3051 0.3051 0.9118 0.4828 0.0105 ...
    # - attr(*, "dimnames")=List of 3
    #  ..$ : NULL
    #  ..$ : chr [1:4] "Estimate" "Est.Error" "Q2.5" "Q97.5"
    #  ..$ : chr [1:3] "P(Y = c4)" "P(Y = c6)" "P(Y = c8)"
    ```

    But with `predict()` you still get level numbers:

    ```r
    str(predict(m_cyl_mpg))
    # num [1:32, 1:3] 0.301 0.3167 0.916 0.4805 0.0115 ...
    # - attr(*, "dimnames")=List of 2
    #  ..$ : NULL
    #  ..$ : chr [1:3] "P(Y = 1)" "P(Y = 2)" "P(Y = 3)"
    ```

2. I think this change may have introduced a bug in `fitted()` when the response variable is an integer in an ordinal model:

    ```r
    m_cyl_mpg_int = brm(cyl ~ mpg, data = mtcars, family = cumulative)
    fitted(m_cyl_mpg_int)
    # Error in dimnames(out) <- `*vtmp*` : 
    #  length of 'dimnames' [3] not equal to array extent
    ```

    I checked in the current CRAN version of brms and the above line works without error.

**Comment by mjskay** [comment]
Also, in a similar vein to point (1), is there / could there be a way to get original levels back with `predict()` when `summary = FALSE`?

E.g., currently the output is:

```r
str(predict(m_cyl_mpg, summary = FALSE))
# num [1:100, 1:32] 2 2 2 2 1 2 2 1 1 1 ...
```

I realize this is perhaps a bit harder as R does not have factor matrices, but perhaps there could be a way to either get a character matrix, or a canonical way to retrieve the levels of the response variable in order to construct one?

**Comment by paul-buerkner** [comment]
Thanks! `fitted` should now be working correctly again.

`predict` still causes me some headaches on how to store the category names. If `summary = TRUE` this is of course possible, but if `summary = FALSE` I don't really know. I am hesitant to add an option to return a character instead of a numeric matrix as this never happens with any other kind of model.

Would it be helpful to add a "levels" attribute to the output of `predict` storing the category names? Or does this feel akward?

**Comment by mjskay** [comment]
Thanks! I've tested it fairly thoroughly and added support for it in tidybayes.

**Comment by paul-buerkner** [comment]
Perfect, thanks for testing! The plots you showed on twitter look great by the way!

**Comment by mjskay** [comment]
Thanks! :)
