### ISSUE TITLE
issue with pp_check for a model with multiple responses and random effect correlations

### ISSUE THREAD

**Issue by lott999** [paul-buerkner/brms#835]
Hi Paul,

I got weird results when plotting the posterior predictive distribution for my model. 

For some context, I have response time data from 3 different tasks performed by the same subjects, in each task there are 2 conditions. As I want to estimate the correlation between the subject level random effects, I aggregated the data from the 3 tasks in a single data frame and added a subset column for each task.

Here is the model 
```
load( file = 'DF_all.RData' )`
    
library('brms')
library('ggplot2')

bf_CORR_XP1 = bf( RT_XP1 | subset(subset_XP1) ~ XP1_COND1 + (XP1_COND1|RCORR|Subject)
                        , beta ~ 1 + (1|Subject)
                ) + exgaussian()
bf_CORR_XP2 = bf( RT_XP2 | subset(subset_XP2) ~ XP2_COND1 + (XP2_COND1|RCORR|Subject)
                        , beta ~ 1 + (1|Subject)
                ) + exgaussian()
bf_CORR_XP3 = bf( RT_XP3 | subset(subset_XP3) ~ XP3_COND1 + (XP3_COND1|RCORR|Subject)
                        , beta ~  1 + (1|Subject)
                ) + exgaussian()



FIT_CORR_order1 = brm( bf_CORR_XP1 + bf_CORR_XP2 + bf_CORR_XP3 + set_rescor(FALSE)
                            , data = DF_all
                            , prior = c( prior( normal(0,0.5) , class = "b" ,  resp = "RTXP1")
                                         , prior( normal(0,0.5) , class = "b" ,  resp = "RTXP2")
                                         , prior( normal(0,0.5) , class = "b" ,  resp = "RTXP3")
                                         , prior( normal(0,1) , class = "sd" , resp = "RTXP1" )
                                         , prior( normal(0,1) , class = "sd" , resp = "RTXP2" )
                                         , prior( normal(0,1) , class = "sd" , resp = "RTXP3" )
                                         , prior( normal(0,0.5) , class = "sigma" ,  resp = "RTXP1")
                                         , prior( normal(0,0.5) , class = "sigma" ,  resp = "RTXP2")
                                         , prior( normal(0,0.5) , class = "sigma" ,  resp = "RTXP3")
                            )
                            , cores = parallel::detectCores()
                            , iter = 2000
                            , warmup = 1000
                            , control = list( adapt_delta = 0.95, max_treedepth = 15 )
                            , file = 'FIT_CORR_order1'
                        )

pp_check(FIT_CORR_order1 , nsamples = 100 , resp = 'RTXP1') + ggtitle('FIT_CORR_order1 resp = RTXP1')
ggsave( 'FIT_CORR_order1_RTXP1.png' )
pp_check(FIT_CORR_order1 , nsamples = 100 , resp = 'RTXP2') + ggtitle('FIT_CORR_order1 resp = RTXP2')
ggsave( 'FIT_CORR_order1_RTXP2.png' )
pp_check(FIT_CORR_order1 , nsamples = 100 , resp = 'RTXP3') + ggtitle('FIT_CORR_order1 resp = RTXP3')
ggsave( 'FIT_CORR_order1_RTXP3.png' )

```
and I got the following plots

![FIT_CORR_order1_RTXP1](https://user-images.githubusercontent.com/60145732/72819364-6dd50400-3c6d-11ea-8c30-615de51881a3.png)
![FIT_CORR_order1_RTXP2](https://user-images.githubusercontent.com/60145732/72819429-87764b80-3c6d-11ea-84be-834fcb9c6fe5.png)
![FIT_CORR_order1_RTXP3](https://user-images.githubusercontent.com/60145732/72819437-8ba26900-3c6d-11ea-9f7d-a535515c8c9a.png)

The one for the RTXP3 response is really weird. Moreover if I perform the fit by changing the order of the formulas and I place the  one for the RT_XP1 response at the end.

```
FIT_CORR_order2 = brm( bf_CORR_XP3 + bf_CORR_XP2 + bf_CORR_XP1 + set_rescor(FALSE)
                  , data = DF_all
                  , prior = c( prior( normal(0,0.5) , class = "b" ,  resp = "RTXP1")
                               , prior( normal(0,0.5) , class = "b" ,  resp = "RTXP2")
                               , prior( normal(0,0.5) , class = "b" ,  resp = "RTXP3")
                               , prior( normal(0,1) , class = "sd" , resp = "RTXP1" )
                               , prior( normal(0,1) , class = "sd" , resp = "RTXP2" )
                               , prior( normal(0,1) , class = "sd" , resp = "RTXP3" )
                               , prior( normal(0,0.5) , class = "sigma" ,  resp = "RTXP1")
                               , prior( normal(0,0.5) , class = "sigma" ,  resp = "RTXP2")
                               , prior( normal(0,0.5) , class = "sigma" ,  resp = "RTXP3")
                  )
                  , cores = parallel::detectCores()
                  , iter = 2000
                  , warmup = 1000
                  , control = list( adapt_delta = 0.99, max_treedepth = 15 )
                  , file = 'FIT_CORR_order2'
)

pp_check(FIT_CORR_order2 , nsamples = 100 , resp = 'RTXP1') + ggplot2::ggtitle('FIT_CORR_order2 resp = RTXP1')
ggsave( 'FIT_CORR_order2_RTXP1.png' )
pp_check(FIT_CORR_order2 , nsamples = 100 , resp = 'RTXP2') + ggplot2::ggtitle('FIT_CORR_order2 resp = RTXP2')
ggsave( 'FIT_CORR_order2_RTXP2.png' )
pp_check(FIT_CORR_order2 , nsamples = 100 , resp = 'RTXP3') + ggplot2::ggtitle('FIT_CORR_order2 resp = RTXP3')
ggsave( 'FIT_CORR_order2_RTXP3.png' )
```
I get

![FIT_CORR_order2_RTXP1](https://user-images.githubusercontent.com/60145732/72819869-49c5f280-3c6e-11ea-8c91-57d443ff567f.png)
![FIT_CORR_order2_RTXP2](https://user-images.githubusercontent.com/60145732/72819883-4f233d00-3c6e-11ea-99e3-4b7962a2da82.png)
![FIT_CORR_order2_RTXP3](https://user-images.githubusercontent.com/60145732/72819894-53e7f100-3c6e-11ea-849b-21f0340b3ac6.png)

and now the one for RTXP1 seems off.

I performed some tests to pin down where the problem arises. First, I do not get the weird behavior if I keep the random effect correlations on the mean but remove the random effect on the beta parameters. Second, I do not get the weird behavior if I remove the random effect correlations on the mean and keep the random effect on the beta parameters.

Here is the data frame and the saved models 
[DF_and_fit_files.zip](https://github.com/paul-buerkner/brms/files/4091982/DF_and_fit_files.zip)

Also, I'm running brms_2.11.1 (compiled from github yesterday) and rstan_2.19.2 on linux.

**Comment by paul-buerkner** [comment]
I think this issue was fixed in the github version of brms. Can you try it
out and report if the new version solves it?

lott999 <notifications@github.com> schrieb am Di., 21. Jan. 2020, 18:09:

**Comment by lott999** [comment]
Did you add some changes since yesterday ? I updated from github just yesterday.

**Comment by paul-buerkner** [comment]
Yeah I did. The new version is 2.11.2

lott999 <notifications@github.com> schrieb am Di., 21. Jan. 2020, 19:05:

**Comment by lott999** [comment]
OK, after updating, restarting R, I tried first by just reloading the saved fit and then by refitting the model but it didn't solve the issue.

**Comment by paul-buerkner** [comment]
You are right, I just fixed it. The problem was that multiple IDs were used across multiple response variables and the implied order of the varying parameters was not as the post-processing methods expected it to be.
