### ISSUE TITLE
custom families post-processing function

### ISSUE THREAD

**Issue by Kreile** [paul-buerkner/brms#921]
Dear All
When repeating the code from the custom families vignette 
https://cran.r-project.org/web/packages/brms/vignettes/brms_customfamilies.html
with 

_R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4_

an error pops up with _log_like_beta_binimial2_ etc., 

_Error in log_lik_fun(i = i, draws = draws) : 
  unused argument (draws = draws)_

As I encountered more issues with stan having updated my Mac software,
it might be connected to that.. (https://discourse.mc-stan.org/t/r-4-0-0-and-cran-macos-binaries/13989/19).

Any Ideas what might went wrong? Thanks a lot in advance

**Comment by paul-buerkner** [comment]
Should be fixed already as of version 2.13. You need to replace "draws" with "prep".

**Comment by Kreile** [comment]
Not quite sure, where do I use do I need to plug it in below (code from vignette)?

_log_lik_beta_binomial2 <- function(i, prep) {
  mu <- prep$dpars$mu[, i]
  phi <- prep$dpars$phi
  trials <- prep$data$vint1[i]
  y <- prep$data$Y[i]
  beta_binomial2_lpmf(y, mu, phi, trials)
}

brms::loo(fit1, fit2)_

**Comment by paul-buerkner** [comment]
Yes. See the latest vignette version.

Kreile <notifications@github.com> schrieb am Mo., 8. Juni 2020, 13:17:

**Comment by Kreile** [comment]
I did, the problem persists. Do I miss something super obvious..

**Comment by paul-buerkner** [comment]
In this case please provide a minimal reproducible example.

Kreile <notifications@github.com> schrieb am Mo., 8. Juni 2020, 13:28:

**Comment by Kreile** [comment]
Just the code of the latest vignette:

_data("cbpp", package = "lme4")

beta_binomial2 <- custom_family(
  "beta_binomial2", dpars = c("mu", "phi"),
  links = c("logit", "log"), lb = c(NA, 0),
  type = "int", vars = "vint1[n]"
)

stan_funs <- "
  real beta_binomial2_lpmf(int y, real mu, real phi, int T) {
    return beta_binomial_lpmf(y | T, mu * phi, (1 - mu) * phi);
  }
  int beta_binomial2_rng(real mu, real phi, int T) {
    return beta_binomial_rng(T, mu * phi, (1 - mu) * phi);
  }
"

stanvars <- stanvar(scode = stan_funs, block = "functions")

fit2 <- brm(
  incidence | vint(size) ~ period + (1|herd), data = cbpp, 
  family = beta_binomial2, stanvars = stanvars, cores = 4
)

expose_functions(fit2, vectorize = TRUE)


log_lik_beta_binomial2 <- function(i, prep) {
  mu <- prep$dpars$mu[, i]
  phi <- prep$dpars$phi
  trials <- prep$data$vint1[i]
  y <- prep$data$Y[i]
  beta_binomial2_lpmf(y, mu, phi, trials)
}

brms::loo(fit1)_

**Comment by Kreile** [comment]
I might add that, with my Mac software, I need to do:

cl <- parallel::makeCluster(2, setup_strategy = "sequential")
if (Sys.getenv("RSTUDIO") == "1" && !nzchar(Sys.getenv("RSTUDIO_TERM")) && 
    Sys.info()["sysname"] == "Darwin" && getRversion() == "4.0.0") {
  parallel:::setDefaultClusterOptions(setup_strategy = "sequential")
}

For reasons I don't really understand myself

**Comment by paul-buerkner** [comment]
The code you provide works for me. Did you update brms to version 2.13?

**Comment by Kreile** [comment]
I did but must have done so in an unclean way, updating does not work somehow. Keeping you posted. Also small error in the code above, it is _loo(fit2)_

**Comment by Kreile** [comment]
Okay works, thanks a lot, also for the awesome work of yours!

**Comment by Kreile** [comment]
Hi - Might I ask if there are more changes necessary compared to the vignette code if there
are (right) censored observations? 

Something like:
log_lik_beta_binomial2 <- function(i, prep) {
mu <- prep$dpars$mu[, i]
phi <- prep$dpars$phi
trials <- prep$data$vint1[i]
y <- prep$data$Y[I]
cens <- prep$data$cens[i]
if(cens == 0{
   beta_binomial2_lpmf(y, mu, phi, trials)
} else{
   beta_binomial2_lccdf(y, mu, phi, trials)
}
}


I also opened a topic on the stan forum for this:
https://discourse.mc-stan.org/t/loo-with-brms-custom-family/15791

**Comment by paul-buerkner** [comment]
Please avoid cross posting and please use the brms tag on stan discourse as otherwise I will likely overlook it (and give me some time to respond)

**Comment by Kreile** [comment]
It's not really cross posting, more a separate issue

**Comment by paul-buerkner** [comment]
I see. Please ask brms related issued on https://discourse.mc-stan.org/ so that other people can find my answers more easily.
